import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Fraunces } from "next/font/google"

const milligram = localFont({
  src: [
    {
      path: "./assets/fonts/Milligram-Regular-trial.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./assets/fonts/Milligram-Medium-trial.ttf",
      weight: "500",
      style: "normal",
    },
  ],
});

const fraunces = Fraunces({
  subsets: ['latin'],
  variable: '--font-fraunces',
  display: 'swap'
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${fraunces.className} ${milligram.className}`}>
      <body>{children}</body>
    </html>
  );
}
